// Code generated by protoc-gen-go. DO NOT EDIT.
// source: filter/filter.proto

package filter

import (
	context "context"
	fmt "fmt"
	pb "github.com/always-waiting/cobra-canal/rpc/pb"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f45b4a1fb0c46f6e, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type BaseInfo struct {
	Status               *pb.Status     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *BaseInfo_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BaseInfo) Reset()         { *m = BaseInfo{} }
func (m *BaseInfo) String() string { return proto.CompactTextString(m) }
func (*BaseInfo) ProtoMessage()    {}
func (*BaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f45b4a1fb0c46f6e, []int{1}
}

func (m *BaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfo.Unmarshal(m, b)
}
func (m *BaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfo.Marshal(b, m, deterministic)
}
func (m *BaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfo.Merge(m, src)
}
func (m *BaseInfo) XXX_Size() int {
	return xxx_messageInfo_BaseInfo.Size(m)
}
func (m *BaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfo proto.InternalMessageInfo

func (m *BaseInfo) GetStatus() *pb.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *BaseInfo) GetData() *BaseInfo_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type BaseInfo_TableFilter struct {
	Db                   string   `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	IncludeTable         []string `protobuf:"bytes,2,rep,name=include_table,json=includeTable,proto3" json:"include_table,omitempty"`
	ExcludeTable         []string `protobuf:"bytes,3,rep,name=exclude_table,json=excludeTable,proto3" json:"exclude_table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfo_TableFilter) Reset()         { *m = BaseInfo_TableFilter{} }
func (m *BaseInfo_TableFilter) String() string { return proto.CompactTextString(m) }
func (*BaseInfo_TableFilter) ProtoMessage()    {}
func (*BaseInfo_TableFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_f45b4a1fb0c46f6e, []int{1, 0}
}

func (m *BaseInfo_TableFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfo_TableFilter.Unmarshal(m, b)
}
func (m *BaseInfo_TableFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfo_TableFilter.Marshal(b, m, deterministic)
}
func (m *BaseInfo_TableFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfo_TableFilter.Merge(m, src)
}
func (m *BaseInfo_TableFilter) XXX_Size() int {
	return xxx_messageInfo_BaseInfo_TableFilter.Size(m)
}
func (m *BaseInfo_TableFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfo_TableFilter.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfo_TableFilter proto.InternalMessageInfo

func (m *BaseInfo_TableFilter) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *BaseInfo_TableFilter) GetIncludeTable() []string {
	if m != nil {
		return m.IncludeTable
	}
	return nil
}

func (m *BaseInfo_TableFilter) GetExcludeTable() []string {
	if m != nil {
		return m.ExcludeTable
	}
	return nil
}

type BaseInfo_Data struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Aggreable            bool                  `protobuf:"varint,2,opt,name=aggreable,proto3" json:"aggreable,omitempty"`
	Filter               *BaseInfo_TableFilter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BaseInfo_Data) Reset()         { *m = BaseInfo_Data{} }
func (m *BaseInfo_Data) String() string { return proto.CompactTextString(m) }
func (*BaseInfo_Data) ProtoMessage()    {}
func (*BaseInfo_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_f45b4a1fb0c46f6e, []int{1, 1}
}

func (m *BaseInfo_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfo_Data.Unmarshal(m, b)
}
func (m *BaseInfo_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfo_Data.Marshal(b, m, deterministic)
}
func (m *BaseInfo_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfo_Data.Merge(m, src)
}
func (m *BaseInfo_Data) XXX_Size() int {
	return xxx_messageInfo_BaseInfo_Data.Size(m)
}
func (m *BaseInfo_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfo_Data proto.InternalMessageInfo

func (m *BaseInfo_Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BaseInfo_Data) GetAggreable() bool {
	if m != nil {
		return m.Aggreable
	}
	return false
}

func (m *BaseInfo_Data) GetFilter() *BaseInfo_TableFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "filter.Request")
	proto.RegisterType((*BaseInfo)(nil), "filter.BaseInfo")
	proto.RegisterType((*BaseInfo_TableFilter)(nil), "filter.BaseInfo.TableFilter")
	proto.RegisterType((*BaseInfo_Data)(nil), "filter.BaseInfo.Data")
}

func init() { proto.RegisterFile("filter/filter.proto", fileDescriptor_f45b4a1fb0c46f6e) }

var fileDescriptor_f45b4a1fb0c46f6e = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x4e, 0xbb, 0x40,
	0x10, 0xc6, 0x0b, 0x34, 0xfc, 0xdb, 0x69, 0xff, 0x6a, 0xd6, 0x98, 0x10, 0xd2, 0x43, 0x83, 0x1e,
	0xf0, 0x00, 0xc4, 0x56, 0x5f, 0xa0, 0x35, 0x1a, 0xaf, 0xab, 0x27, 0x2f, 0x66, 0x16, 0x16, 0x5c,
	0x43, 0x01, 0x61, 0x49, 0xf5, 0xbd, 0x7c, 0x40, 0xc3, 0xb2, 0x8d, 0x8d, 0xf6, 0x04, 0x7c, 0xfc,
	0xe6, 0x9b, 0xfd, 0x66, 0x07, 0x4e, 0x53, 0x91, 0x4b, 0x5e, 0x47, 0xfd, 0x23, 0xac, 0xea, 0x52,
	0x96, 0xc4, 0xee, 0xbf, 0x5c, 0x60, 0xd8, 0xf0, 0x5e, 0xf3, 0x02, 0xf8, 0x47, 0xf9, 0x7b, 0xcb,
	0x1b, 0x49, 0x08, 0x0c, 0x0b, 0xdc, 0x70, 0xc7, 0x98, 0x1b, 0xfe, 0x98, 0xaa, 0x77, 0x72, 0x04,
	0xa6, 0x48, 0x1c, 0x73, 0x6e, 0xf8, 0x16, 0x35, 0x45, 0xe2, 0x7d, 0x99, 0x30, 0x5a, 0x61, 0xc3,
	0x1f, 0x8a, 0xb4, 0x24, 0x17, 0x60, 0x37, 0x12, 0x65, 0xdb, 0xa8, 0x92, 0xc9, 0x62, 0x1a, 0x2a,
	0xe3, 0x47, 0xa5, 0x51, 0xfd, 0x8f, 0x5c, 0xc2, 0x30, 0x41, 0x89, 0xca, 0x64, 0xb2, 0x38, 0x0b,
	0xf5, 0x91, 0x76, 0x2e, 0xe1, 0x2d, 0x4a, 0xa4, 0x0a, 0x71, 0x33, 0x98, 0x3c, 0x21, 0xcb, 0xf9,
	0x9d, 0x42, 0xba, 0xe6, 0x09, 0xd3, 0xc7, 0x31, 0x13, 0x46, 0xce, 0xe1, 0xbf, 0x28, 0xe2, 0xbc,
	0x4d, 0xf8, 0x8b, 0xec, 0x30, 0xc7, 0x9c, 0x5b, 0xfe, 0x98, 0x4e, 0xb5, 0xa8, 0x4a, 0x3b, 0x88,
	0x7f, 0xec, 0x43, 0x56, 0x0f, 0x69, 0x51, 0x41, 0x6e, 0x01, 0xc3, 0xae, 0xed, 0xc1, 0xc8, 0x33,
	0x18, 0x63, 0x96, 0xd5, 0x5c, 0x77, 0x30, 0xfc, 0x11, 0xfd, 0x11, 0xc8, 0x35, 0xe8, 0x29, 0x3a,
	0x96, 0xca, 0x33, 0xfb, 0x93, 0x67, 0x2f, 0x01, 0xd5, 0xec, 0xe2, 0x0d, 0x6c, 0x9d, 0xe9, 0x0a,
	0xa0, 0x23, 0x29, 0xaf, 0xca, 0x5a, 0x92, 0xe3, 0x5d, 0xb5, 0xbe, 0x03, 0xf7, 0xe4, 0xb7, 0x9d,
	0x37, 0x20, 0x01, 0xd8, 0xf7, 0x5c, 0xae, 0xd3, 0xec, 0x10, 0xae, 0x26, 0x4e, 0x79, 0x53, 0xad,
	0xcb, 0x22, 0x15, 0x99, 0x37, 0x58, 0xdd, 0x3c, 0x2f, 0x33, 0x21, 0x5f, 0x5b, 0x16, 0xc6, 0xe5,
	0x26, 0xc2, 0x7c, 0x8b, 0x9f, 0x4d, 0xb0, 0x45, 0x21, 0x45, 0x91, 0x45, 0x71, 0xc9, 0x6a, 0x0c,
	0x62, 0x2c, 0x30, 0x8f, 0xea, 0x2a, 0x8e, 0x2a, 0xa6, 0x57, 0x84, 0xd9, 0x6a, 0x1f, 0x96, 0xdf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x6e, 0x46, 0x9f, 0x3a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FilterClient is the client API for Filter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FilterClient interface {
	BaseReport(ctx context.Context, in *Request, opts ...grpc.CallOption) (*BaseInfo, error)
	GetCfg(ctx context.Context, in *Request, opts ...grpc.CallOption) (*pb.RespConfig, error)
}

type filterClient struct {
	cc *grpc.ClientConn
}

func NewFilterClient(cc *grpc.ClientConn) FilterClient {
	return &filterClient{cc}
}

func (c *filterClient) BaseReport(ctx context.Context, in *Request, opts ...grpc.CallOption) (*BaseInfo, error) {
	out := new(BaseInfo)
	err := c.cc.Invoke(ctx, "/filter.Filter/BaseReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filterClient) GetCfg(ctx context.Context, in *Request, opts ...grpc.CallOption) (*pb.RespConfig, error) {
	out := new(pb.RespConfig)
	err := c.cc.Invoke(ctx, "/filter.Filter/GetCfg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilterServer is the server API for Filter service.
type FilterServer interface {
	BaseReport(context.Context, *Request) (*BaseInfo, error)
	GetCfg(context.Context, *Request) (*pb.RespConfig, error)
}

// UnimplementedFilterServer can be embedded to have forward compatible implementations.
type UnimplementedFilterServer struct {
}

func (*UnimplementedFilterServer) BaseReport(ctx context.Context, req *Request) (*BaseInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaseReport not implemented")
}
func (*UnimplementedFilterServer) GetCfg(ctx context.Context, req *Request) (*pb.RespConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCfg not implemented")
}

func RegisterFilterServer(s *grpc.Server, srv FilterServer) {
	s.RegisterService(&_Filter_serviceDesc, srv)
}

func _Filter_BaseReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilterServer).BaseReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/filter.Filter/BaseReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilterServer).BaseReport(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filter_GetCfg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilterServer).GetCfg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/filter.Filter/GetCfg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilterServer).GetCfg(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Filter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "filter.Filter",
	HandlerType: (*FilterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BaseReport",
			Handler:    _Filter_BaseReport_Handler,
		},
		{
			MethodName: "GetCfg",
			Handler:    _Filter_GetCfg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "filter/filter.proto",
}
