[[rules]]# 处理工厂
id = 1 # 工厂标识符
desc = "工厂简单描述"
queue_addr = "amqp://guest:guest@localhost:5672/cobra" # 队列地址
[rules.log]
type="file"
level = "debug"
dirname = "/export/Logs/cobra"
[rules.db] # 主库链接配置
user = "user"
password = "passwd"
db = "db"
addr = "addr"
[rules.err]
type = "fake" # 错误处理类型

[rules.filtermanage] # 过滤经理配置
name = "filtername" # 经理的标识
desc = "说明"
[rules.filtermanage.tablefilter]
db_name = "db_cmdb"
include_table = ["t_device_basic", "t_device_config"]

[[rules.filtermanage.worker]] # 过滤工人配置
filter_type = "base" # 加载用户自定义的过滤
max = 10
[rules.filtermanage.worker.tablefilter]
db_name = "db_cmdb"
include_table = ["t_device_basic", "t_device_config"]
[rules.filtermanage.worker.aggregation]
time = 10
[[rules.filtermanage.worker.aggregation.idxrule]]
tables = ["t_device_basic"]
idx_field = "id"
exclude_field = ["action_id"]

[rules.transfermanage] # 转换经理配置
name = "transfername"
desc = "说明"
[[rules.transfermanage.workers]] # 转换工人配置
transfer_type = "base"
[[rules.transfermanage.workers]] # 转换工人配置
transfer_type = "base"
