[cobra]
rebase = true
buffer = 1000
[cobra.config]# 监控binlog
addr = "localhost:3306" # 监控的主库
user = "root"
password = "abc123"
server_id = 90000000 # 从库唯一id标识
include_table_regex = ["db_cmdb\\..*", "db_cmdb_cobra\\.*"]
[cobra.db]
addr = "localhost:3306"
user = "root"
password = "abc123"
db = "db_cmdb_cobra"


[[rules]]# 处理工厂
id = 1 # 工厂标识符
desc = "工厂简单描述"
queue_addr = "amqp://guest:guest@localhost:5672/cobra" # 队列地址
#[rules.log]
#type="file"
#level = "debug"
#dirname = "/export/Logs/cobra"
#[rules.db] # 主库链接配置
#$user = "user"
#$password = "passwd"
#$db = "db"
#$addr = "addr"
#$[rules.err]
#$type = "fake" # 错误处理类型
[rules.filtermanage] # 过滤经理配置
name = "filtername" # 经理的标识
desc = "说明"
db_required = true # 是否需要主库链接
[rules.filtermanage.tablefilter]
db_name = "db_cmdb"
include_table = ["t_device_basic", "t_device_config"]
[rules.filtermanage.aggregation]
time = 10
[[rules.filtermanage.aggregation.idxrule]]
tables = ["t_device_basic"]
idx_field = "id"
exclude_field = ["action_id"]
[rules.filtermanage.worker] # 过滤工人配置
filter_type = "base" # 加载用户自定义的过滤
max = 10
