// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitor/monitor.proto

package monitor

import (
	context "context"
	fmt "fmt"
	pb "github.com/always-waiting/cobra-canal/rpc/pb"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("monitor/monitor.proto", fileDescriptor_94d5950496a7550d) }

var fileDescriptor_94d5950496a7550d = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0xcd, 0xcf, 0xcb,
	0x2c, 0xc9, 0x2f, 0xd2, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0xae,
	0x14, 0x57, 0x52, 0x62, 0x71, 0x2a, 0x44, 0xd0, 0xc8, 0x94, 0x8b, 0xcd, 0x37, 0x31, 0x2f, 0x31,
	0x3d, 0x55, 0x48, 0x9b, 0x8b, 0xcd, 0x3d, 0xb5, 0xc4, 0x39, 0x2d, 0x5d, 0x88, 0x57, 0x0f, 0xac,
	0x20, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x4a, 0x00, 0xc6, 0x2d, 0x2e, 0x70, 0xce, 0xcf,
	0x4b, 0xcb, 0x4c, 0x57, 0x62, 0x70, 0x32, 0x8b, 0x32, 0x49, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2,
	0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0xcc, 0x29, 0x4f, 0xac, 0x2c, 0xd6, 0x2d, 0x4f, 0xcc, 0x2c, 0xc9,
	0xcc, 0x4b, 0xd7, 0x4f, 0xce, 0x4f, 0x2a, 0x4a, 0xd4, 0x4d, 0x4e, 0xcc, 0x4b, 0xcc, 0xd1, 0x2f,
	0x2a, 0x48, 0xd6, 0x2f, 0x48, 0x82, 0xb9, 0x24, 0x89, 0x0d, 0x6c, 0xab, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0xc0, 0x54, 0x0b, 0xd1, 0xa3, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ManageClient is the client API for Manage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManageClient interface {
	GetCfg(ctx context.Context, in *pb.Request, opts ...grpc.CallOption) (*pb.RespConfig, error)
}

type manageClient struct {
	cc *grpc.ClientConn
}

func NewManageClient(cc *grpc.ClientConn) ManageClient {
	return &manageClient{cc}
}

func (c *manageClient) GetCfg(ctx context.Context, in *pb.Request, opts ...grpc.CallOption) (*pb.RespConfig, error) {
	out := new(pb.RespConfig)
	err := c.cc.Invoke(ctx, "/monitor.Manage/GetCfg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManageServer is the server API for Manage service.
type ManageServer interface {
	GetCfg(context.Context, *pb.Request) (*pb.RespConfig, error)
}

// UnimplementedManageServer can be embedded to have forward compatible implementations.
type UnimplementedManageServer struct {
}

func (*UnimplementedManageServer) GetCfg(ctx context.Context, req *pb.Request) (*pb.RespConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCfg not implemented")
}

func RegisterManageServer(s *grpc.Server, srv ManageServer) {
	s.RegisterService(&_Manage_serviceDesc, srv)
}

func _Manage_GetCfg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManageServer).GetCfg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor.Manage/GetCfg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManageServer).GetCfg(ctx, req.(*pb.Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Manage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.Manage",
	HandlerType: (*ManageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCfg",
			Handler:    _Manage_GetCfg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitor/monitor.proto",
}
