// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitor.proto

package monitor

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MonitorRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MonitorRequest) Reset()         { *m = MonitorRequest{} }
func (m *MonitorRequest) String() string { return proto.CompactTextString(m) }
func (*MonitorRequest) ProtoMessage()    {}
func (*MonitorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{0}
}

func (m *MonitorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorRequest.Unmarshal(m, b)
}
func (m *MonitorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorRequest.Marshal(b, m, deterministic)
}
func (m *MonitorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorRequest.Merge(m, src)
}
func (m *MonitorRequest) XXX_Size() int {
	return xxx_messageInfo_MonitorRequest.Size(m)
}
func (m *MonitorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorRequest proto.InternalMessageInfo

func (m *MonitorRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{1}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BaseInfo struct {
	Data                 *BaseInfo_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status               *Status        `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BaseInfo) Reset()         { *m = BaseInfo{} }
func (m *BaseInfo) String() string { return proto.CompactTextString(m) }
func (*BaseInfo) ProtoMessage()    {}
func (*BaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{2}
}

func (m *BaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfo.Unmarshal(m, b)
}
func (m *BaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfo.Marshal(b, m, deterministic)
}
func (m *BaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfo.Merge(m, src)
}
func (m *BaseInfo) XXX_Size() int {
	return xxx_messageInfo_BaseInfo.Size(m)
}
func (m *BaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfo proto.InternalMessageInfo

func (m *BaseInfo) GetData() *BaseInfo_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BaseInfo) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type BaseInfo_Data struct {
	Slave                string   `protobuf:"bytes,1,opt,name=slave,proto3" json:"slave,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	ServerId             uint64   `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	IncludeTableRegex    []string `protobuf:"bytes,4,rep,name=includeTableRegex,proto3" json:"includeTableRegex,omitempty"`
	ExcludeTableRegex    []string `protobuf:"bytes,5,rep,name=excludeTableRegex,proto3" json:"excludeTableRegex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfo_Data) Reset()         { *m = BaseInfo_Data{} }
func (m *BaseInfo_Data) String() string { return proto.CompactTextString(m) }
func (*BaseInfo_Data) ProtoMessage()    {}
func (*BaseInfo_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{2, 0}
}

func (m *BaseInfo_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfo_Data.Unmarshal(m, b)
}
func (m *BaseInfo_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfo_Data.Marshal(b, m, deterministic)
}
func (m *BaseInfo_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfo_Data.Merge(m, src)
}
func (m *BaseInfo_Data) XXX_Size() int {
	return xxx_messageInfo_BaseInfo_Data.Size(m)
}
func (m *BaseInfo_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfo_Data proto.InternalMessageInfo

func (m *BaseInfo_Data) GetSlave() string {
	if m != nil {
		return m.Slave
	}
	return ""
}

func (m *BaseInfo_Data) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *BaseInfo_Data) GetServerId() uint64 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *BaseInfo_Data) GetIncludeTableRegex() []string {
	if m != nil {
		return m.IncludeTableRegex
	}
	return nil
}

func (m *BaseInfo_Data) GetExcludeTableRegex() []string {
	if m != nil {
		return m.ExcludeTableRegex
	}
	return nil
}

func init() {
	proto.RegisterType((*MonitorRequest)(nil), "monitor.MonitorRequest")
	proto.RegisterType((*Status)(nil), "monitor.Status")
	proto.RegisterType((*BaseInfo)(nil), "monitor.BaseInfo")
	proto.RegisterType((*BaseInfo_Data)(nil), "monitor.BaseInfo.Data")
}

func init() { proto.RegisterFile("monitor.proto", fileDescriptor_44174b7b2a306b71) }

var fileDescriptor_44174b7b2a306b71 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x35, 0x6d, 0x9a, 0x34, 0x53, 0xaa, 0x74, 0x11, 0x0d, 0xf5, 0x12, 0x82, 0x60, 0x10, 0xc9,
	0x21, 0x82, 0x07, 0x8f, 0xa2, 0x87, 0x1e, 0xbc, 0xac, 0xde, 0x65, 0xdb, 0x8c, 0x25, 0x90, 0x64,
	0x6b, 0x76, 0x53, 0xfa, 0x0f, 0x7e, 0x89, 0x7f, 0x29, 0x3b, 0x9b, 0x14, 0x34, 0xb7, 0x37, 0xfb,
	0xde, 0x9b, 0x7d, 0x33, 0x03, 0xf3, 0x4a, 0xd6, 0x85, 0x96, 0x4d, 0xba, 0x6b, 0xa4, 0x96, 0xcc,
	0xef, 0xca, 0xf8, 0x1a, 0x4e, 0x5f, 0x2d, 0xe4, 0xf8, 0xd5, 0xa2, 0xd2, 0x8c, 0x81, 0x5b, 0x8b,
	0x0a, 0x43, 0x27, 0x72, 0x92, 0x80, 0x13, 0x8e, 0x1f, 0xc0, 0x7b, 0xd3, 0x42, 0xb7, 0xca, 0xb0,
	0x1b, 0x99, 0x5b, 0x76, 0xc2, 0x09, 0xb3, 0x10, 0xfc, 0x0a, 0x95, 0x12, 0x5b, 0x0c, 0x47, 0x64,
	0xea, 0xcb, 0xf8, 0x7b, 0x04, 0xd3, 0x27, 0xa1, 0x70, 0x55, 0x7f, 0x4a, 0x76, 0x0b, 0x6e, 0x2e,
	0xb4, 0x20, 0xeb, 0x2c, 0xbb, 0x48, 0xfb, 0x44, 0xbd, 0x20, 0x7d, 0x16, 0x5a, 0x70, 0xd2, 0xb0,
	0x1b, 0xf0, 0x14, 0x7d, 0x48, 0x1d, 0x67, 0xd9, 0xd9, 0x51, 0x6d, 0x73, 0xf0, 0x8e, 0x5e, 0xfe,
	0x38, 0xe0, 0x1a, 0x1f, 0x3b, 0x87, 0x89, 0x2a, 0xc5, 0xbe, 0xcf, 0x6d, 0x0b, 0x13, 0x77, 0x27,
	0x1b, 0x4d, 0x5d, 0xe6, 0x9c, 0x30, 0xbb, 0x82, 0x40, 0x61, 0xb3, 0xc7, 0xe6, 0xa3, 0xc8, 0xc3,
	0x71, 0xe4, 0x24, 0x2e, 0x9f, 0xda, 0x87, 0x55, 0xce, 0xee, 0x60, 0x51, 0xd4, 0x9b, 0xb2, 0xcd,
	0xf1, 0x5d, 0xac, 0x4b, 0xe4, 0xb8, 0xc5, 0x43, 0xe8, 0x46, 0xe3, 0x24, 0xe0, 0x43, 0xc2, 0xa8,
	0xf1, 0xf0, 0x5f, 0x3d, 0xb1, 0xea, 0x01, 0x91, 0xbd, 0x80, 0xdf, 0xed, 0x9a, 0x3d, 0x02, 0x98,
	0xb1, 0x39, 0x52, 0xa2, 0xcb, 0xe3, 0x74, 0x7f, 0x6f, 0xb1, 0x5c, 0x0c, 0x96, 0x14, 0x9f, 0xac,
	0x3d, 0x3a, 0xe1, 0xfd, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76, 0xdc, 0xde, 0x5c, 0xd3, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MonitorClient is the client API for Monitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonitorClient interface {
	BaseReport(ctx context.Context, in *MonitorRequest, opts ...grpc.CallOption) (*BaseInfo, error)
}

type monitorClient struct {
	cc *grpc.ClientConn
}

func NewMonitorClient(cc *grpc.ClientConn) MonitorClient {
	return &monitorClient{cc}
}

func (c *monitorClient) BaseReport(ctx context.Context, in *MonitorRequest, opts ...grpc.CallOption) (*BaseInfo, error) {
	out := new(BaseInfo)
	err := c.cc.Invoke(ctx, "/monitor.Monitor/BaseReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorServer is the server API for Monitor service.
type MonitorServer interface {
	BaseReport(context.Context, *MonitorRequest) (*BaseInfo, error)
}

// UnimplementedMonitorServer can be embedded to have forward compatible implementations.
type UnimplementedMonitorServer struct {
}

func (*UnimplementedMonitorServer) BaseReport(ctx context.Context, req *MonitorRequest) (*BaseInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaseReport not implemented")
}

func RegisterMonitorServer(s *grpc.Server, srv MonitorServer) {
	s.RegisterService(&_Monitor_serviceDesc, srv)
}

func _Monitor_BaseReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).BaseReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor.Monitor/BaseReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).BaseReport(ctx, req.(*MonitorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Monitor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.Monitor",
	HandlerType: (*MonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BaseReport",
			Handler:    _Monitor_BaseReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitor.proto",
}
