// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RespConfig struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Config               []byte   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespConfig) Reset()         { *m = RespConfig{} }
func (m *RespConfig) String() string { return proto.CompactTextString(m) }
func (*RespConfig) ProtoMessage()    {}
func (*RespConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}

func (m *RespConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespConfig.Unmarshal(m, b)
}
func (m *RespConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespConfig.Marshal(b, m, deterministic)
}
func (m *RespConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespConfig.Merge(m, src)
}
func (m *RespConfig) XXX_Size() int {
	return xxx_messageInfo_RespConfig.Size(m)
}
func (m *RespConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RespConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RespConfig proto.InternalMessageInfo

func (m *RespConfig) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RespConfig) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Status)(nil), "base.Status")
	proto.RegisterType((*RespConfig)(nil), "base.RespConfig")
	proto.RegisterType((*Request)(nil), "base.Request")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150) }

var fileDescriptor_db1b6b0986796150 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0x50, 0x52, 0xf5, 0xa8, 0x18, 0x3c, 0xa0, 0x8c, 0x55, 0xc4, 0xd0, 0x81, 0xc4,
	0x12, 0x48, 0xfc, 0x00, 0xd8, 0x18, 0x8f, 0x8d, 0xed, 0xec, 0x18, 0x63, 0xa9, 0xb1, 0x4d, 0xce,
	0x51, 0xc5, 0xbf, 0x47, 0xbd, 0xb6, 0xdb, 0x7b, 0xba, 0x7b, 0xdf, 0xbd, 0x03, 0x30, 0xc4, 0x6e,
	0xc8, 0x73, 0x2a, 0x49, 0xad, 0x4e, 0xba, 0x7b, 0x85, 0xe6, 0xb3, 0x50, 0x59, 0x58, 0x29, 0x58,
	0xd9, 0x34, 0xba, 0xb6, 0xda, 0x55, 0xfb, 0x5b, 0x14, 0xad, 0x5a, 0x58, 0x4f, 0x8e, 0x99, 0xbc,
	0x6b, 0xeb, 0x5d, 0xb5, 0xdf, 0xe0, 0xd5, 0x76, 0x1f, 0x00, 0xe8, 0x38, 0xbf, 0xa7, 0xf8, 0x1d,
	0xbc, 0x7a, 0x84, 0x86, 0x85, 0x22, 0xe9, 0xbb, 0xe7, 0xed, 0x20, 0x87, 0xce, 0x64, 0xbc, 0xcc,
	0xd4, 0x03, 0x34, 0x56, 0xf6, 0x05, 0xb6, 0xc5, 0x8b, 0xeb, 0x7a, 0x58, 0xa3, 0xfb, 0x5d, 0x1c,
	0x97, 0x53, 0x89, 0x48, 0xd3, 0xb9, 0xc4, 0x06, 0x45, 0xab, 0x7b, 0xa8, 0xc3, 0x28, 0x91, 0x1b,
	0xac, 0xc3, 0xf8, 0x36, 0x7c, 0x3d, 0xf9, 0x50, 0x7e, 0x16, 0x33, 0xd8, 0x34, 0x69, 0x3a, 0x1c,
	0xe9, 0x8f, 0xfb, 0x23, 0x85, 0x12, 0xa2, 0xd7, 0x36, 0x99, 0x99, 0x7a, 0x4b, 0x91, 0x0e, 0x7a,
	0xce, 0x56, 0x67, 0x63, 0x1a, 0xf9, 0xf7, 0xe5, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x10, 0xb3, 0x2e,
	0x30, 0xfd, 0x00, 0x00, 0x00,
}
