// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manage.proto

package filter

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FilterRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterRequest) Reset()         { *m = FilterRequest{} }
func (m *FilterRequest) String() string { return proto.CompactTextString(m) }
func (*FilterRequest) ProtoMessage()    {}
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{0}
}

func (m *FilterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterRequest.Unmarshal(m, b)
}
func (m *FilterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterRequest.Marshal(b, m, deterministic)
}
func (m *FilterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterRequest.Merge(m, src)
}
func (m *FilterRequest) XXX_Size() int {
	return xxx_messageInfo_FilterRequest.Size(m)
}
func (m *FilterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilterRequest proto.InternalMessageInfo

func (m *FilterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FilterRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{1}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BaseInfo struct {
	Status               *Status        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *BaseInfo_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BaseInfo) Reset()         { *m = BaseInfo{} }
func (m *BaseInfo) String() string { return proto.CompactTextString(m) }
func (*BaseInfo) ProtoMessage()    {}
func (*BaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{2}
}

func (m *BaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfo.Unmarshal(m, b)
}
func (m *BaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfo.Marshal(b, m, deterministic)
}
func (m *BaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfo.Merge(m, src)
}
func (m *BaseInfo) XXX_Size() int {
	return xxx_messageInfo_BaseInfo.Size(m)
}
func (m *BaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfo proto.InternalMessageInfo

func (m *BaseInfo) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *BaseInfo) GetData() *BaseInfo_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type BaseInfo_TableFilter struct {
	Db                   string   `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	IncludeTable         []string `protobuf:"bytes,2,rep,name=include_table,json=includeTable,proto3" json:"include_table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfo_TableFilter) Reset()         { *m = BaseInfo_TableFilter{} }
func (m *BaseInfo_TableFilter) String() string { return proto.CompactTextString(m) }
func (*BaseInfo_TableFilter) ProtoMessage()    {}
func (*BaseInfo_TableFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{2, 0}
}

func (m *BaseInfo_TableFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfo_TableFilter.Unmarshal(m, b)
}
func (m *BaseInfo_TableFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfo_TableFilter.Marshal(b, m, deterministic)
}
func (m *BaseInfo_TableFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfo_TableFilter.Merge(m, src)
}
func (m *BaseInfo_TableFilter) XXX_Size() int {
	return xxx_messageInfo_BaseInfo_TableFilter.Size(m)
}
func (m *BaseInfo_TableFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfo_TableFilter.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfo_TableFilter proto.InternalMessageInfo

func (m *BaseInfo_TableFilter) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *BaseInfo_TableFilter) GetIncludeTable() []string {
	if m != nil {
		return m.IncludeTable
	}
	return nil
}

type BaseInfo_Data struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Aggreable            bool                  `protobuf:"varint,2,opt,name=aggreable,proto3" json:"aggreable,omitempty"`
	Filter               *BaseInfo_TableFilter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BaseInfo_Data) Reset()         { *m = BaseInfo_Data{} }
func (m *BaseInfo_Data) String() string { return proto.CompactTextString(m) }
func (*BaseInfo_Data) ProtoMessage()    {}
func (*BaseInfo_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{2, 1}
}

func (m *BaseInfo_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfo_Data.Unmarshal(m, b)
}
func (m *BaseInfo_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfo_Data.Marshal(b, m, deterministic)
}
func (m *BaseInfo_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfo_Data.Merge(m, src)
}
func (m *BaseInfo_Data) XXX_Size() int {
	return xxx_messageInfo_BaseInfo_Data.Size(m)
}
func (m *BaseInfo_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfo_Data proto.InternalMessageInfo

func (m *BaseInfo_Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BaseInfo_Data) GetAggreable() bool {
	if m != nil {
		return m.Aggreable
	}
	return false
}

func (m *BaseInfo_Data) GetFilter() *BaseInfo_TableFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func init() {
	proto.RegisterType((*FilterRequest)(nil), "filter.FilterRequest")
	proto.RegisterType((*Status)(nil), "filter.Status")
	proto.RegisterType((*BaseInfo)(nil), "filter.BaseInfo")
	proto.RegisterType((*BaseInfo_TableFilter)(nil), "filter.BaseInfo.TableFilter")
	proto.RegisterType((*BaseInfo_Data)(nil), "filter.BaseInfo.Data")
}

func init() { proto.RegisterFile("manage.proto", fileDescriptor_519fa8ed5ffbbc8f) }

var fileDescriptor_519fa8ed5ffbbc8f = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xcd, 0xb6, 0xc6, 0x66, 0xd2, 0x16, 0x59, 0x10, 0x42, 0xe8, 0x21, 0x44, 0x90, 0x78,
	0xc9, 0x21, 0x15, 0x3d, 0x5b, 0x44, 0xf0, 0xba, 0x7a, 0x97, 0x49, 0x77, 0x1a, 0x02, 0xf9, 0x53,
	0xb3, 0x9b, 0x0f, 0xe2, 0x37, 0x96, 0x6c, 0x36, 0xfe, 0xbf, 0xcd, 0xce, 0xfe, 0xde, 0xe3, 0xcd,
	0x0c, 0x2c, 0x6b, 0x6c, 0xb0, 0xa0, 0xf4, 0xd8, 0xb5, 0xba, 0xe5, 0xee, 0xa1, 0xac, 0x34, 0x75,
	0xf1, 0x16, 0x56, 0x8f, 0xa6, 0x12, 0xf4, 0xd6, 0x93, 0xd2, 0x9c, 0xc3, 0xbc, 0xc1, 0x9a, 0x02,
	0x27, 0x72, 0x12, 0x4f, 0x98, 0x9a, 0xaf, 0x81, 0x95, 0x32, 0x60, 0x91, 0x93, 0xcc, 0x04, 0x2b,
	0x65, 0x7c, 0x0b, 0xee, 0xb3, 0x46, 0xdd, 0xab, 0x81, 0xde, 0xb7, 0x72, 0xa4, 0x4f, 0x85, 0xa9,
	0x79, 0x00, 0x67, 0x35, 0x29, 0x85, 0x05, 0x19, 0x89, 0x27, 0xa6, 0x67, 0xfc, 0xce, 0x60, 0xb1,
	0x43, 0x45, 0x4f, 0xcd, 0xa1, 0xe5, 0x57, 0xe0, 0x2a, 0x63, 0x62, 0xc4, 0x7e, 0xb6, 0x4e, 0xc7,
	0x48, 0xe9, 0x68, 0x2d, 0xec, 0x2f, 0xbf, 0x86, 0xb9, 0x44, 0x8d, 0xc6, 0xcb, 0xcf, 0x2e, 0x26,
	0x6a, 0xf2, 0x49, 0x1f, 0x50, 0xa3, 0x30, 0x48, 0xb8, 0x03, 0xff, 0x05, 0xf3, 0x8a, 0xc6, 0x89,
	0x86, 0xd8, 0x32, 0xb7, 0x83, 0x30, 0x99, 0xf3, 0x4b, 0x58, 0x95, 0xcd, 0xbe, 0xea, 0x25, 0xbd,
	0xea, 0x01, 0x0b, 0x58, 0x34, 0x4b, 0x3c, 0xb1, 0xb4, 0x4d, 0x23, 0x0d, 0x1b, 0x98, 0x0f, 0x8e,
	0xff, 0xee, 0x61, 0x03, 0x1e, 0x16, 0x45, 0x47, 0x56, 0xec, 0x24, 0x0b, 0xf1, 0xd5, 0xe0, 0x37,
	0x60, 0x97, 0x1a, 0xcc, 0x4c, 0xd4, 0xcd, 0x9f, 0xa8, 0xdf, 0xc2, 0x09, 0xcb, 0x66, 0xf7, 0xe0,
	0xda, 0xb8, 0x77, 0x00, 0x03, 0x29, 0xe8, 0xd8, 0x76, 0x9a, 0x7f, 0x0e, 0xfa, 0xe3, 0x3c, 0xe1,
	0xf9, 0x6f, 0xd3, 0xf8, 0x24, 0x77, 0xcd, 0x49, 0xb7, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd2,
	0x4c, 0xdd, 0x48, 0xe2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FilterClient is the client API for Filter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FilterClient interface {
	BaseReport(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*BaseInfo, error)
}

type filterClient struct {
	cc *grpc.ClientConn
}

func NewFilterClient(cc *grpc.ClientConn) FilterClient {
	return &filterClient{cc}
}

func (c *filterClient) BaseReport(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*BaseInfo, error) {
	out := new(BaseInfo)
	err := c.cc.Invoke(ctx, "/filter.Filter/BaseReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilterServer is the server API for Filter service.
type FilterServer interface {
	BaseReport(context.Context, *FilterRequest) (*BaseInfo, error)
}

// UnimplementedFilterServer can be embedded to have forward compatible implementations.
type UnimplementedFilterServer struct {
}

func (*UnimplementedFilterServer) BaseReport(ctx context.Context, req *FilterRequest) (*BaseInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaseReport not implemented")
}

func RegisterFilterServer(s *grpc.Server, srv FilterServer) {
	s.RegisterService(&_Filter_serviceDesc, srv)
}

func _Filter_BaseReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilterServer).BaseReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/filter.Filter/BaseReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilterServer).BaseReport(ctx, req.(*FilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Filter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "filter.Filter",
	HandlerType: (*FilterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BaseReport",
			Handler:    _Filter_BaseReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manage.proto",
}
