[canal]
addr = "localhost:3306"
user = "root"
password = "abc123"
server_id = 10000000
include_table_regex = ["db_test\\..*"]

[mysql]
addr = "localhost:3306"
user = "root"
password = "abc123"
db = "db_cmdb_cobra"

